messenger4j:
  appSecret: 3fa7b22e5c78f669bf83b0ec00f283fb
  verifyToken : Ali_Spring_Wassouf
  pageAccessToken: EAAaSMpnn2OQBAI1g3TP0gnith02IowCsj9ZBMjuocu5SKAlQnZAZAzDlucEWgh3DuJCfCGKj9SE7NqPWlCZCzZAr8ynLF8nTlE84nt6m3oon6qr0KQogH92rZAUoSFAeWuL7L8P7TZAdZBqxMV4ENo7irtvFStfKprD73gdAhbunnncQZCiQHZBKRAHQlQ1HmDZC5YZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
