messenger4j:
  appSecret: a199b1c2b25281afbf63a7322762b394
  verifyToken : Ali_Spring_Wassouf
  pageAccessToken: EAACMRty3GZCYBABqkpm5Q2hdtMScisv0hvfuz7qIGQq5Rl2lsYHujRoX79TKLRqMrdwpaZARxppAgjbxXRUg4WnCyOD03ZAXHiVj10PhmBsjFLkZCZBV7BrRZCwQ1P2xbHZBnj19RAonVGddiBl1ZCAhAZCFYmmUcVy0n045d0sm0pZClanR6rhWrK

logging:
  level:
    com:
      github:
        messenger4j: INFO
