messenger4j:
  appSecret: a199b1c2b25281afbf63a7322762b394
  verifyToken : Ali_Spring_Wassouf
  pageAccessToken: EAACMRty3GZCYBAI69cZCW2nosUlx2rZBKKmXpiUGiVeCiYjGnhDcLLX9oZCyZCZCobJyozdwxswU9TZBCbDZA3HJrPuQd14YG5Haf7tlD16S7ZAEXAoJhXxp5eTKadoVSie3UBFWSEY0IWhZCkOmRXgysJQFR4Nw1daBJJDb4sXiWUeq5W9PPd1B02

logging:
  level:
    com:
      github:
        messenger4j: INFO
